; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:m5stick-c-plus]
platform = espressif32@6.8.1
board = m5stick-c
framework = arduino

; Serial monitor speed
monitor_speed = 115200

lib_deps =
    m5stack/M5StickCPlus @ ^0.0.8
    knolleary/PubSubClient @ ^2.8
    mikalhart/TinyGPSPlus @ ^1.0.3
    plerup/EspSoftwareSerial @ ^8.0.1
